language: node_js
node_js:
  - "6"

script:
 - npm run coverage

after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

before_deploy:
  - zip -r master-${TRAVIS_BUILD_NUMBER}.zip ./*

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "visual-character-bucket"
    zip_file: master-${TRAVIS_BUILD_NUMBER}.zip
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "visual-character-bucket"
    region: us-west-2
    s3_key: master-${TRAVIS_BUILD_NUMBER}.zip
    # key: ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tgz
    application: "visual-character_code-deploy"
    deployment_group: "visual-character"
