language: node_js
node_js:
  - "6"

scripts:
 - npm run test-cov

after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API
