language: node_js
node_js:
  - "6"

script:
 - npm run coverage

after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "visual-character-bucket"
    region: us-west-2
    key: latest/app.zip
    application: "visual-character"
    deployment_group: "visual-character_deployment-group"
